# Generated by Django 4.2.28 on 2026-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_body_remove_article_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='Тут будет текст статьи'),
            preserve_default=False,
        ),
    ]
