# Generated by Django 4.2.28 on 2026-02-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
